npm install @bigfunger/decompress-zip
npm install     @spalger/angular-bootstrap
npm install     @spalger/filesaver
npm install     @spalger/leaflet-draw
npm install     @spalger/leaflet-heat
npm install     @spalger/numeral
npm install     @spalger/test-subj-selector
npm install     @spalger/ui-ace
npm install     angular
npm install     angular-bootstrap-colorpicker
npm install     angular-elastic
npm install     angular-route
npm install     angular-sanitize
npm install     ansicolors
npm install     autoprefixer
npm install     autoprefixer-loader
npm install     babel
npm install     babel-core
npm install     babel-loader
npm install     babel-runtime
npm install     bluebird
npm install     boom
npm install     bootstrap
npm install     brace
npm install     bunyan
npm install     clipboard
npm install     commander
npm install     css-loader
npm install     d3
npm install     elasticsearch
npm install     elasticsearch-browser
npm install     expiry-js
npm install     exports-loader
npm install     expose-loader
npm install     extract-text-webpack-plugin
npm install     file-loader
npm install     font-awesome
npm install     good
npm install     good-squeeze
npm install     gridster
npm install     hapi
npm install     imports-loader
npm install     jade
npm install     jade-loader
npm install     joi
npm install     jquery
npm install     js-yaml
npm install     json-loader
npm install     json-stringify-safe
npm install     jstimezonedetect
npm install     leaflet
npm install     less
npm install     less-loader
npm install     loader-utils
npm install     lodash
npm install     marked
npm install     minimatch
npm install     mkdirp
npm install     moment
npm install     moment-timezone
npm install     raw-loader
npm install     request
npm install     requirefrom
npm install     rimraf
npm install     rjs-repack-loader
npm install     script-loader
npm install     semver
npm install     style-loader
npm install     tar
npm install     url-loader
npm install     webpack
npm install     webpack-directory-name-as-main
npm install     whatwg-fetch
npm install     wreck

npm install     Nonsense
npm install     angular-mocks
npm install     auto-release-sinon
npm install     babel-eslint
npm install     chokidar
npm install     chromedriver
npm install     eslint
npm install     eslint-plugin-mocha
npm install     expect.js
npm install     faker
npm install     glob
npm install     grunt
npm install     grunt-babel
npm install     grunt-cli
npm install     grunt-contrib-clean
npm install     grunt-contrib-copy
npm install     grunt-esvm
npm install     grunt-karma
npm install     grunt-run
npm install     grunt-s3
npm install     grunt-simple-mocha
npm install     gruntify-eslint
npm install     husky
npm install     intern
npm install     istanbul-instrumenter-loader
npm install     karma
npm install     karma-chrome-launcher
npm install     karma-coverage
npm install     karma-firefox-launcher
npm install     karma-ie-launcher
npm install     karma-mocha
npm install     karma-safari-launcher
npm install     libesvm
npm install     license-checker
npm install     load-grunt-config
npm install     makelogs
npm install     mocha
npm install     nock
npm install     npm
npm install     portscanner
npm install     simple-git
npm install     sinon
npm install     source-map
